POST http://localhost:8080/devops_starter_war_exploded/api/login

{"username": "user","password": "test12113"}

###
GET http://localhost:8080/exam_war_exploded/api/race/car/all

###
POST http://localhost:8080/exam_war_exploded/api/driver

{name: "testCreate", birthYear: "2022", experience: "none", gender: "male", userName:"testUsername", password:"test123"}}

###
DELETE http://localhost:8080/exam_war_exploded/api/race/5